Repository prgrms-web-devcourse/Team-PODO-ODEEGO-BE, pull requests merged in 2023-03, with the labels that each got.

#26 [ODE-56] 로그인 재구현 및 JWT 인증 필터 구현
  build.gradle
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/web/api/auth/AuthApi.java
  src/main/java/podo/odeego/web/api/auth/dto/GetMemberInfoRequest.java
  src/main/java/podo/odeego/web/api/auth/dto/GetMemberInfoResponse.java
  src/main/java/podo/odeego/web/api/auth/dto/MemberLoginResponse.java
  src/main/java/podo/odeego/web/api/auth/dto/OAuth2GetTokenResponse.java
  src/main/java/podo/odeego/web/api/hello/HelloAuthApi.java
  src/main/java/podo/odeego/web/security/config/WebSecurityConfig.java
  src/main/java/podo/odeego/web/security/filter/JwtAuthenticationFilter.java
  src/main/java/podo/odeego/web/security/jwt/JwtAuthenticationPrincipal.java
  src/main/java/podo/odeego/web/security/jwt/JwtAuthenticationToken.java
  src/main/java/podo/odeego/web/security/jwt/JwtProvider.java
  src/main/java/podo/odeego/web/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  src/main/java/podo/odeego/web/security/oauth2/OAuth2LoginResponse.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
Labels: ✨Feat, ♻️Refactor

#25 [HOTFIX]: 요구사항으로 인한 코드 수정
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointSearchRequest.java
  src/main/java/podo/odeego/domain/station/dto/StationResponse.java
Labels: ♻️Refactor, 🔥Hotfix

#27 [ODE-65] Member 엔티티 필드 추가
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/entity/MemberType.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
Labels: ♻️Refactor

#28 [ODE-68] 회원의 모든 모임 조회 API
  src/main/java/podo/odeego/domain/group/dto/response/GroupResponses.java
  src/main/java/podo/odeego/domain/group/dto/response/SimpleGroupResponse.java
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/main/java/podo/odeego/domain/group/service/GroupQueryService.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/web/api/group/v1/GroupApi.java
  src/main/java/podo/odeego/web/api/group/v1/GroupTestApi.java
  src/main/java/podo/odeego/web/error/ErrorResponse.java
  src/main/java/podo/odeego/web/error/GlobalExceptionHandler.java
  src/main/resources/generated-requests.http
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
Labels: ✨Feat, 📜Docs

#33 [HOTFIX] 그룹 멤버가 제대로 추가가 안되는 오류 수정
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
Labels: 🔥Hotfix

#32 [ODE-63] 회원의 기본 역 가져오는 API
  src/main/java/podo/odeego/domain/member/dto/MemberDefaultStationGetResponse.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/service/MemberFindService.java
  src/main/java/podo/odeego/web/api/member/MemberApi.java
  src/test/java/podo/odeego/config/TestConfig.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
  src/test/java/podo/odeego/domain/member/service/MemberFindServiceTest.java
Labels: ✨Feat, ♻️Refactor, ✅Test

#36 [ODE-9] 회원가입 시 추가정보 입력 API 구현
  src/main/java/podo/odeego/domain/member/dto/MemberJoinResponse.java
  src/main/java/podo/odeego/domain/member/dto/MemberSignUpRequest.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/exception/MemberNicknameDuplicatedException.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/web/api/auth/AuthApi.java
  src/main/java/podo/odeego/web/api/auth/dto/MemberLoginResponse.java
  src/main/java/podo/odeego/web/api/member/MemberApi.java
  src/test/java/podo/odeego/config/TestConfig.java
  src/test/java/podo/odeego/domain/member/service/MemberServiceTest.java
Labels: ✨Feat, ♻️Refactor

#37 [ODE-9] 설정값 분리
  src/main/java/podo/odeego/web/api/auth/AuthApi.java
Labels: ♻️Refactor

#40 Refactor(logging): Request, Response URL을 로깅하도록 변경
  src/main/java/podo/odeego/web/logging/ApiLogInterceptor.java
Labels: ♻️Refactor

#42 [ODE-73] 예외 원인을 명세하기 위한 커스텀 에러 코드 구현
  src/main/java/podo/odeego/domain/group/entity/GroupCapacity.java
  src/main/java/podo/odeego/domain/group/exception/AlreadyParticipatingGroupException.java
  src/main/java/podo/odeego/domain/group/exception/GroupAlreadyContainsException.java
  src/main/java/podo/odeego/domain/group/exception/GroupAlreadyFullException.java
  src/main/java/podo/odeego/domain/group/exception/GroupCapacityOutOfBoundsException.java
  src/main/java/podo/odeego/domain/group/exception/GroupHostAbsentException.java
  src/main/java/podo/odeego/domain/group/exception/GroupNotFoundException.java
  src/main/java/podo/odeego/domain/member/exception/MemberNicknameDuplicatedException.java
  src/main/java/podo/odeego/domain/member/exception/MemberNotFoundException.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/domain/place/domain/PlaceCategory.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/global/error/ErrorCode.java
  src/main/java/podo/odeego/global/error/ErrorResponse.java
  src/main/java/podo/odeego/global/error/GlobalExceptionHandler.java
  src/main/java/podo/odeego/global/error/exception/AlreadyFullException.java
  src/main/java/podo/odeego/global/error/exception/BusinessException.java
  src/main/java/podo/odeego/global/error/exception/InvalidValueException.java
  src/main/java/podo/odeego/global/error/exception/ResourceNotFoundException.java
  src/main/java/podo/odeego/web/error/ErrorCode.java
  src/main/java/podo/odeego/web/error/exception/AlreadyFullException.java
  src/main/java/podo/odeego/web/error/exception/EntityNotFoundException.java
  src/main/java/podo/odeego/web/error/exception/ResourceNotFoundException.java
Labels: ♻️Refactor

#44 Revert "Chore(CD): 핫픽스를 위한 workflow 변경"
  .github/workflows/release.yml
Labels: 🚀CI/CD

#43 [ODE-9] 회원가입 기능 리팩토링
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/exception/DefaultStationNotExistsException.java
  src/main/java/podo/odeego/domain/member/exception/MemberNicknameOutOfBoundsException.java
  src/main/java/podo/odeego/domain/member/exception/MemberNicknameUnformattedException.java
  src/main/java/podo/odeego/domain/member/repository/MemberRepository.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/domain/station/exception/StationNotFoundException.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/global/error/ErrorCode.java
  src/main/java/podo/odeego/web/api/auth/AuthApi.java
  src/test/java/podo/odeego/config/TestConfig.java
  src/test/java/podo/odeego/domain/member/entity/MemberTest.java
  src/test/java/podo/odeego/domain/member/service/MemberServiceTest.java
Labels: ✨Feat, ♻️Refactor

#45 HOTFIX: 영속화된 시간값을 읽을 때 외부 환경에 영향 받지 않도록 애플리케이션 TimeZone 설정
  src/main/java/podo/odeego/OdeegoApplication.java
  src/main/java/podo/odeego/domain/util/TimeUtils.java
Labels: 🔥Hotfix

#46 [ODE-76] 회원 탈퇴 API
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/web/api/member/MemberTestApi.java
  src/main/java/podo/odeego/web/api/member/v1/MemberApi.java
  src/test/java/podo/odeego/domain/member/service/MemberServiceTest.java
Labels: ✨Feat

#49 [HOTFIX] 요구사항에 따른 직렬화 방식 변경
  src/main/java/podo/odeego/domain/group/dto/HostStationModifyRequest.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointSearchRequest.java
  src/main/java/podo/odeego/domain/midpoint/dto/StartSubmitRequest.java
  src/main/java/podo/odeego/domain/util/JsonUtils.java
Labels: 🔥Hotfix

#48 [ODE-78] 장소, 장소 이미지 엔티티 객체 설계
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponses.java
  src/main/java/podo/odeego/domain/place/dto/PlaceResponses.java
  src/main/java/podo/odeego/domain/place/entity/Place.java
  src/main/java/podo/odeego/domain/place/entity/PlaceCategory.java
  src/main/java/podo/odeego/domain/place/entity/PlaceImage.java
  src/main/java/podo/odeego/domain/place/exception/PlaceCategoryNotValidException.java
  src/main/java/podo/odeego/domain/place/exception/PlaceImageDuplicatedException.java
  src/main/java/podo/odeego/domain/place/repository/PlaceImageRepository.java
  src/main/java/podo/odeego/domain/place/repository/PlaceRepository.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryService.java
  src/main/java/podo/odeego/domain/station/dto/StationNameQueryDto.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/domain/type/Address.java
  src/main/java/podo/odeego/domain/type/Image.java
  src/main/java/podo/odeego/infra/openapi/naver/ClientRequest.java
  src/main/java/podo/odeego/infra/openapi/naver/NaverClient.java
  src/main/java/podo/odeego/infra/openapi/naver/NaverPlaceQueryService.java
  src/main/java/podo/odeego/infra/openapi/naver/dto/LocalSearchRequest.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/ImageSearchClient.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/dto/ImageSearchRequest.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/dto/ImageSearchResponse.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/client/LocalSearchClient.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/dto/LocalSearchQueryDto.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/dto/LocalSearchRequest.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/dto/LocalSearchResponse.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/dto/PlaceQueryDto.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/service/NaverPlaceQueryService.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/util/PlaceDataParser.java
  src/main/java/podo/odeego/web/api/place/converter/PlaceCategoryConverter.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/main/resources/generated-requests.http
  src/test/java/podo/odeego/infra/openapi/naver/LocalSearchClientTest.java
  src/test/java/podo/odeego/infra/openapi/naver/NaverClientTest.java
  src/test/java/podo/odeego/infra/openapi/naver/imagesearch/ImageSearchClientTest.java
Labels: ✨Feat, ♻️Refactor, 📜Docs, ✅Test

#50 [ODE-92] 로그인 기능 리팩토링
  src/main/java/podo/odeego/domain/member/dto/MemberJoinResponse.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/main/java/podo/odeego/global/error/ErrorResponse.java
  src/main/java/podo/odeego/global/error/GlobalExceptionHandler.java
  src/main/java/podo/odeego/infra/openapi/kakao/KakaoClient.java
  src/main/java/podo/odeego/infra/openapi/kakao/dto/GetUserInfoResponse.java
  src/main/java/podo/odeego/infra/openapi/kakao/dto/KakaoProfileResponse.java
  src/main/java/podo/odeego/infra/openapi/kakao/exception/KakaoClientErrorException.java
  src/main/java/podo/odeego/web/api/auth/AuthApi.java
  src/main/java/podo/odeego/web/api/auth/dto/GetMemberInfoRequest.java
  src/main/java/podo/odeego/web/api/auth/dto/MemberLoginResponse.java
  src/main/java/podo/odeego/web/api/auth/dto/OAuth2GetTokenResponse.java
  src/main/java/podo/odeego/web/api/hello/HelloAuthApi.java
  src/main/java/podo/odeego/web/security/AuthorizationComponent.java
  src/main/java/podo/odeego/web/security/jwt/JwtProvider.java
  src/main/java/podo/odeego/web/security/jwt/dto/GenerateTokenResponse.java
  src/test/java/podo/odeego/infra/openapi/naver/LocalSearchClientTest.java
  src/test/java/podo/odeego/infra/openapi/naver/imagesearch/ImageSearchClientTest.java
Labels: ✨Feat, ♻️Refactor

#51 [ODE-94] 장소, 이미지 데이터를 영속화합니다.
  src/main/java/podo/odeego/domain/place/dto/PlaceCreateRequest.java
  src/main/java/podo/odeego/domain/place/dto/PlaceImageAddRequest.java
  src/main/java/podo/odeego/domain/place/dto/PlaceImageCreateRequest.java
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/domain/place/entity/Place.java
  src/main/java/podo/odeego/domain/place/entity/PlaceImage.java
  src/main/java/podo/odeego/domain/place/exception/PlaceNotFoundException.java
  src/main/java/podo/odeego/domain/place/repository/PlaceRepository.java
  src/main/java/podo/odeego/domain/place/service/PlaceCreateService.java
  src/main/java/podo/odeego/domain/place/service/PlaceImageAddService.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/podo/odeego/domain/station/dto/StationNameQueryDto.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/domain/type/Image.java
  src/main/java/podo/odeego/global/error/ErrorCode.java
  src/main/java/podo/odeego/global/error/GlobalExceptionHandler.java
  src/main/java/podo/odeego/global/error/exception/NonBusinessException.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/client/ImageSearchClient.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/dto/ImageQueryDto.java
  src/main/java/podo/odeego/infra/openapi/naver/imagesearch/dto/ImageSearchResponse.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/dto/LocalSearchQueryDto.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/util/PlaceDataParser.java
  src/main/java/podo/odeego/infra/scaping/place/PlaceImageScraper.java
  src/main/java/podo/odeego/infra/scaping/place/PlaceScraper.java
  src/main/java/podo/odeego/infra/scaping/place/util/TimeSleeper.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/main/java/podo/odeego/web/api/scraping/ScrapingApi.java
  src/main/java/podo/odeego/web/api/scraping/exception/NotAuthorizedException.java
Labels: ✨Feat, ♻️Refactor, 🔮Fix, ✅Test

#52 [HOTFIX] open api 사용량 한도로 인해, 영속화된 데이터를 사용하도록 변경
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
Labels: 🔥Hotfix

#54 [ODE-81] 장소 조회 시 응답에 이미지 URL 을 포함합니다
  src/main/java/podo/odeego/domain/place/dto/PlaceImageUrl.java
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/domain/place/entity/Place.java
Labels: ✨Feat

#55 [HOTFIX] 역에서 주소 정보 삭제
  build.gradle
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointResponse.java
  src/main/java/podo/odeego/domain/station/dto/StationResponse.java
  src/main/java/podo/odeego/domain/station/entity/Station.java
  src/test/java/podo/odeego/domain/group/entity/GroupMemberTest.java
  src/test/java/podo/odeego/domain/group/entity/GroupTest.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberModifyServiceTest.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberValidateServiceTest.java
  src/test/java/podo/odeego/domain/member/service/MemberFindServiceTest.java
  src/test/java/podo/odeego/domain/member/service/MemberServiceTest.java
Labels: 🔥Hotfix

#57 [ODE-82] 장소 조회 API 호출 시 페이징 기반으로 응답합니다.
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/domain/place/repository/PlaceRepository.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryService.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/service/NaverPlaceQueryService.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/main/resources/generated-requests.http
  src/test/java/podo/odeego/config/TestConfig.java
  src/test/java/podo/odeego/domain/place/service/PlaceQueryServiceImplTest.java
Labels: ♻️Refactor, 📜Docs

#59 [ODE-110] 중간 지점 찾기 API 성능 최적화 및 로직 변경
  src/main/java/podo/odeego/domain/group/dto/GroupMemberStation.java
  src/main/java/podo/odeego/domain/group/service/GroupMemberModifyService.java
  src/main/java/podo/odeego/domain/group/service/GroupMemberValidateService.java
  src/main/java/podo/odeego/domain/member/dto/MemberDefaultStationGetResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointSearchResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/NormalizedPathsToEnd.java
  src/main/java/podo/odeego/domain/midpoint/dto/PathsByEnd.java
  src/main/java/podo/odeego/domain/midpoint/service/MidPointConvertService.java
  src/main/java/podo/odeego/domain/midpoint/service/MidPointQueryService.java
  src/main/java/podo/odeego/domain/midpoint/service/MidpointEstimateService.java
  src/main/java/podo/odeego/domain/path/dto/PathInfo.java
  src/main/java/podo/odeego/domain/path/dto/PathResponse.java
  src/main/java/podo/odeego/domain/path/dto/PathStatistics.java
  src/main/java/podo/odeego/domain/path/entity/Path.java
  src/main/java/podo/odeego/domain/path/repository/PathRepository.java
  src/main/java/podo/odeego/domain/path/service/PathConvertService.java
  src/main/java/podo/odeego/domain/path/service/PathFindService.java
  src/main/java/podo/odeego/domain/station/dto/StationInfo.java
  src/main/java/podo/odeego/domain/station/dto/StationResponse.java
  src/main/java/podo/odeego/domain/station/entity/Station.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberValidateServiceTest.java
  src/test/java/podo/odeego/domain/member/service/MemberFindServiceTest.java
Labels: ♻️Refactor

#61 HOTFIX: 중간 지점 찾기 장애 대응 및 인터셉터 설정 변경
  src/main/java/podo/odeego/domain/util/JsonUtils.java
  src/main/java/podo/odeego/web/auth/config/JwtAuthenticationConfig.java
  src/main/java/podo/odeego/web/config/WebMvcConfig.java
  src/main/java/podo/odeego/web/logging/config/ApiLoggerConfig.java
Labels: ♻️Refactor, 🔥Hotfix, 🔮Fix

#63 [ODE-84] 장소 조회 시 응답에 공유 링크를 포함합니다
  src/main/java/podo/odeego/domain/place/dto/PlaceQueryResponse.java
  src/main/java/podo/odeego/domain/place/entity/Place.java
  src/main/java/podo/odeego/domain/type/Address.java
Labels: ✨Feat

#64 [긴급 기능 추가] 그룹 멤버가 그룹에 출발지 제출했는지 확인하는 API 구현
  src/main/java/podo/odeego/domain/group/dto/GroupMemberExistResponse.java
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/main/java/podo/odeego/domain/group/repository/GroupRepository.java
  src/main/java/podo/odeego/domain/group/service/GroupQueryService.java
  src/main/java/podo/odeego/web/api/group/v1/GroupApi.java
  src/test/java/podo/odeego/domain/group/service/GroupQueryServiceTest.java
Labels: ✨Feat

#65 [Refactor] 이미 정회원인 경우 발생시키는 예외 변경
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/entity/MemberAlreadyRegularException.java
  src/main/java/podo/odeego/global/error/ErrorCode.java
  src/test/java/podo/odeego/domain/member/entity/MemberTest.java
Labels: ♻️Refactor

#66 [HOTFIX] 그룹 아이디에 해당하는 그룹을 제대로 가져오지 않은 장애 해결
  src/main/java/podo/odeego/domain/group/repository/GroupRepository.java
Labels: 🔥Hotfix, 🔮Fix

#67 [ODE-117] 회원 탈퇴 시 연관된 그룹 정보도 같이 삭제하도록 변경
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/main/java/podo/odeego/domain/group/repository/GroupMemberRepository.java
  src/main/java/podo/odeego/domain/group/repository/GroupRepository.java
  src/main/java/podo/odeego/domain/group/service/GroupRemoveService.java
  src/main/java/podo/odeego/domain/member/service/MemberService.java
  src/test/java/podo/odeego/config/TestConfig.java
  src/test/java/podo/odeego/domain/group/service/GroupRemoveServiceTest.java
  src/test/java/podo/odeego/domain/member/service/MemberServiceTest.java
Labels: ✨Feat, ♻️Refactor, 🔮Fix, ✅Test

#68 [ODE-120] 논리적으로 존재하지 않는 장소 카테고리 제거
  src/main/java/podo/odeego/domain/place/dto/PlaceCreateRequest.java
  src/main/java/podo/odeego/domain/place/entity/Place.java
  src/main/java/podo/odeego/domain/place/entity/PlaceCategory.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryService.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryServiceImpl.java
  src/main/java/podo/odeego/infra/openapi/naver/localsearch/service/NaverPlaceQueryService.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/test/java/podo/odeego/domain/place/service/PlaceQueryServiceImplTest.java
Labels: ♻️Refactor

#69 [ODE-118] Rest Docs 적용
  build.gradle
  src/docs/asciidoc/api-docs.adoc
  src/main/resources/static/docs/api-docs.html
  src/test/java/podo/odeego/web/api/member/MemberApiTest.java
Labels: 📜Docs, ✅Test
