Repository prgrms-web-devcourse/Team-PODO-ODEEGO-BE, pull requests merged in 2023-02, with the labels that each got.

#6 [ODE-42] CORS 설정을 추가하였습니다
  src/main/java/podo/odeego/web/api/hello/HelloApi.java
  src/main/java/podo/odeego/web/config/WebMvcConfig.java
Labels: ✨Feat

#7 [ODE-31] 전역 예외 처리 포맷 구현
  src/main/java/podo/odeego/web/error/ErrorCode.java
  src/main/java/podo/odeego/web/error/ErrorResponse.java
  src/main/java/podo/odeego/web/error/GlobalExceptionHandler.java
  src/main/java/podo/odeego/web/error/exception/BusinessException.java
  src/main/java/podo/odeego/web/error/exception/InvalidValueException.java
Labels: ✨Feat

#8 [ODE-10] open api 를 이용한 주변 장소 추천 API 구현
  .gitignore
  build.gradle
  src/main/java/podo/odeego/domain/place/domain/PlaceCategory.java
  src/main/java/podo/odeego/domain/place/dto/PlaceResponses.java
  src/main/java/podo/odeego/domain/place/dto/SimplePlaceResponse.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryService.java
  src/main/java/podo/odeego/domain/subway/dto/StationInfo.java
  src/main/java/podo/odeego/infra/openapi/naver/NaverClient.java
  src/main/java/podo/odeego/infra/openapi/naver/NaverPlaceQueryService.java
  src/main/java/podo/odeego/infra/openapi/naver/dto/LocalSearchRequest.java
  src/main/java/podo/odeego/infra/openapi/naver/dto/LocalSearchResponse.java
  src/main/java/podo/odeego/infra/openapi/naver/util/PlaceDataParser.java
  src/main/java/podo/odeego/web/api/place/converter/PlaceCategoryConverter.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/main/java/podo/odeego/web/config/WebConfig.java
  src/main/resources/generated-requests.http
  src/test/java/podo/odeego/infra/openapi/naver/NaverClientTest.java
Labels: ✨Feat, ♻️Refactor

#15 [ODE-34] 중간 지점 구하는 api 구현
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointSearchRequest.java
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointSearchResponse.java
  src/main/java/podo/odeego/domain/midpoint/dto/PathsByEnd.java
  src/main/java/podo/odeego/domain/midpoint/service/MidPointService.java
  src/main/java/podo/odeego/domain/midpoint/vo/PathStatistics.java
  src/main/java/podo/odeego/domain/path/dto/PathResponse.java
  src/main/java/podo/odeego/domain/path/entity/Path.java
  src/main/java/podo/odeego/domain/path/repository/PathRepository.java
  src/main/java/podo/odeego/domain/path/service/PathFindService.java
  src/main/java/podo/odeego/domain/place/service/PlaceQueryService.java
  src/main/java/podo/odeego/domain/station/dto/StationInfo.java
  src/main/java/podo/odeego/domain/station/dto/StationResponse.java
  src/main/java/podo/odeego/domain/station/entity/Station.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/infra/openapi/naver/NaverPlaceQueryService.java
  src/main/java/podo/odeego/web/api/midpoint/MidPointApi.java
  src/main/java/podo/odeego/web/api/place/v1/PlaceApi.java
  src/main/java/podo/odeego/web/error/ErrorCode.java
  src/main/java/podo/odeego/web/error/exception/EntityNotFoundException.java
Labels: ✨Feat, ♻️Refactor

#16 Refactor(Entity): 비즈니스 정책에 따른 타입 변경
  build.gradle
  src/main/java/podo/odeego/domain/midpoint/dto/MidPointResponse.java
  src/main/java/podo/odeego/domain/station/entity/Station.java
Labels: ♻️Refactor

#18 [ODE-34] 중간 지점 구하는 api 리팩토링 및 오류 수정
  src/main/java/podo/odeego/domain/midpoint/service/MidPointConvertService.java
  src/main/java/podo/odeego/domain/midpoint/service/MidPointQueryService.java
  src/main/java/podo/odeego/domain/midpoint/service/MidpointEstimateService.java
  src/main/java/podo/odeego/domain/midpoint/vo/PathStatistics.java
  src/main/java/podo/odeego/domain/path/dto/PathResponse.java
  src/main/java/podo/odeego/domain/path/dto/PathStatistics.java
  src/main/java/podo/odeego/domain/path/entity/Path.java
  src/main/java/podo/odeego/domain/path/service/PathConvertService.java
  src/main/java/podo/odeego/domain/path/service/PathFindService.java
  src/main/java/podo/odeego/domain/station/dto/StationResponse.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/domain/station/service/StationFindService.java
  src/main/java/podo/odeego/web/api/midpoint/MidPointApi.java
Labels: ♻️Refactor, 🔮Fix

#19 [ODE-60] 모임 도메인 객체 및 모임 생성 API 구현
  src/main/java/podo/odeego/OdeegoApplication.java
  src/main/java/podo/odeego/domain/group/dto/request/GroupCreateRequest.java
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/main/java/podo/odeego/domain/group/entity/GroupCapacity.java
  src/main/java/podo/odeego/domain/group/exception/AlreadyParticipatingGroupException.java
  src/main/java/podo/odeego/domain/group/exception/GroupNotFoundException.java
  src/main/java/podo/odeego/domain/group/repository/GroupRepository.java
  src/main/java/podo/odeego/domain/group/service/GroupCreateService.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/member/exception/MemberNotFoundException.java
  src/main/java/podo/odeego/domain/member/service/MemberQueryService.java
  src/main/java/podo/odeego/domain/type/BaseTime.java
  src/main/java/podo/odeego/domain/util/TimeUtils.java
  src/main/java/podo/odeego/web/api/group/v1/GroupApi.java
  src/main/java/podo/odeego/web/config/WebConfig.java
  src/main/java/podo/odeego/web/config/WebMvcConfig.java
  src/main/java/podo/odeego/web/error/GlobalExceptionHandler.java
  src/main/java/podo/odeego/web/error/exception/ResourceNotFoundException.java
  src/test/java/podo/odeego/domain/group/service/GroupCreateServiceTest.java
Labels: ✨Feat

#22 HOTFIX: DB 예약어 사용으로 인해 생기는 문제 수정
  src/main/java/podo/odeego/domain/group/entity/Group.java
Labels: 🔥Hotfix

#21 [ODE-49] 출발지 제출 API 구현
  src/main/java/podo/odeego/domain/group/entity/Group.java
  src/main/java/podo/odeego/domain/group/entity/GroupCapacity.java
  src/main/java/podo/odeego/domain/group/entity/GroupMember.java
  src/main/java/podo/odeego/domain/group/exception/AlreadyParticipatingGroupException.java
  src/main/java/podo/odeego/domain/group/exception/GroupAlreadyContainsException.java
  src/main/java/podo/odeego/domain/group/exception/GroupAlreadyFullException.java
  src/main/java/podo/odeego/domain/group/service/GroupMemberAddService.java
  src/main/java/podo/odeego/domain/member/entity/Member.java
  src/main/java/podo/odeego/domain/midpoint/dto/StartSubmitRequest.java
  src/main/java/podo/odeego/domain/station/entity/Station.java
  src/main/java/podo/odeego/domain/station/repository/StationRepository.java
  src/main/java/podo/odeego/web/api/midpoint/MidPointApi.java
  src/main/java/podo/odeego/web/error/ErrorCode.java
  src/main/java/podo/odeego/web/error/exception/AlreadyFullException.java
  src/test/java/podo/odeego/domain/group/service/GroupMemberAddServiceTest.java
Labels: ✨Feat
